Repository elegantframework/elegant-cli, pull requests merged in 2023-05, with the labels that each got.

#26 Added Storybook JS with darkmode support
  source/elegant/.storybook/main.ts
  source/elegant/.storybook/preview.ts
  source/elegant/package-lock.json
  source/elegant/package.json
  source/elegant/src/components/DarkModeSwitch.js
  source/elegant/src/components/Header.js
  source/elegant/src/components/ThemeToggle.js
  source/elegant/src/components/core/Headers/SplashHeader.stories.tsx
  source/elegant/src/components/core/Headers/SplashHeader.test.tsx
  source/elegant/src/components/core/Headers/SplashHeader.tsx
  source/elegant/src/components/core/Headers/VersionSwitcher.test.tsx
  source/elegant/src/components/core/Headers/VersionSwitcher.tsx
  source/elegant/src/components/core/Headers/__snapshots__/SplashHeader.test.tsx.snap
  source/elegant/src/components/core/Headers/__snapshots__/VersionSwitcher.test.tsx.snap
  source/elegant/src/components/core/Icons/GitHubIcon/GitHubIcon.stories.tsx
  source/elegant/src/components/core/Icons/GitHubIcon/GitHubIcon.test.tsx
  source/elegant/src/components/core/Icons/GitHubIcon/GitHubIcon.tsx
  source/elegant/src/components/core/Icons/GitHubIcon/__snapshots__/GitHubIcon.test.tsx.snap
  source/elegant/src/components/core/Icons/MoonIcon/MoonIcon.stories.tsx
  source/elegant/src/components/core/Icons/MoonIcon/MoonIcon.test.tsx
  source/elegant/src/components/core/Icons/MoonIcon/MoonIcon.tsx
  source/elegant/src/components/core/Icons/MoonIcon/__snapshots__/MoonIcon.test.tsx.snap
  source/elegant/src/components/core/Icons/PCIcon/PCIcon.stories.tsx
  source/elegant/src/components/core/Icons/PCIcon/PCIcon.test.tsx
  source/elegant/src/components/core/Icons/PCIcon/PCIcon.tsx
  source/elegant/src/components/core/Icons/PCIcon/__snapshots__/PCIcon.test.tsx.snap
  source/elegant/src/components/core/Icons/SunIcon/SunIcon.stories.tsx
  source/elegant/src/components/core/Icons/SunIcon/SunIcon.test.tsx
  source/elegant/src/components/core/Icons/SunIcon/SunIcon.tsx
  source/elegant/src/components/core/Icons/SunIcon/__snapshots__/SunIcon.test.tsx.snap
  source/elegant/src/components/core/Navigation/NavItems/NavItems.stories.tsx
  source/elegant/src/components/core/Navigation/NavItems/NavItems.test.tsx
  source/elegant/src/components/core/Navigation/NavItems/NavItems.tsx
  source/elegant/src/components/core/Navigation/NavItems/__snapshots__/NavItems.test.tsx.snap
  source/elegant/src/components/core/Navigation/NavPopover/NavPopover.stories.tsx
  source/elegant/src/components/core/Navigation/NavPopover/NavPopover.test.tsx
  source/elegant/src/components/core/Navigation/NavPopover/NavPopover.tsx
  source/elegant/src/components/core/Navigation/NavPopover/__snapshots__/NavPopover.test.tsx.snap
  source/elegant/src/components/core/Toggles/ThemeToggle/ThemeToggle.stories.tsx
  source/elegant/src/components/core/Toggles/ThemeToggle/ThemeToggle.test.tsx
  source/elegant/src/components/core/Toggles/ThemeToggle/ThemeToggle.tsx
  source/elegant/src/components/core/Toggles/ThemeToggle/__snapshots__/ThemeToggle.test.tsx.snap
  source/elegant/src/layouts/SplashPageLayout.js
  source/elegant/src/pages/404.js
  source/elegant/src/pages/_app.js
  source/elegant/src/pages/docs/release-notes.mdx
  source/elegant/src/pages/index.js
  source/elegant/src/types/NavigationItem.ts
  source/elegant/src/utils/core/Analytics/gtag.js
  source/elegant/src/utils/core/Meta/MetaTitle.test.ts
  source/elegant/src/utils/core/Meta/MetaTitle.ts
  source/elegant/src/utils/core/Text/TextToKebabCase.test.ts
  source/elegant/src/utils/core/Text/TextToKebabCase.ts
  source/elegant/src/utils/core/Text/TextToTitleCase.test.ts
  source/elegant/src/utils/core/Text/TextToTitleCase.ts
  source/elegant/src/utils/themeToggle.js
Labels: type: enhancement, version: 2.2, status: waiting review

#27 Added sitemap with robots.txt file.
  source/elegant/next-sitemap.config.js
  source/elegant/package-lock.json
  source/elegant/package.json
  source/elegant/src/pages/docs/release-notes.mdx
Labels: type: enhancement, version: 2.2, status: waiting review

#29 Update release-notes
  source/elegant/src/pages/docs/release-notes.mdx
Labels: type: enhancement, version: 2.2, status: waiting review

#32 Install package dependencies automatically during init step
  source/elegant/package-lock.json
  source/elegant/package.json
  source/init.js
Labels: type: enhancement, type: friction, version: 2.2, status: waiting on public comment

#35 Update the console.log output during project creation.
  source/init.js
Labels: type: enhancement, version: 2.2, status: waiting on public comment

#37 Create the .env starter file, and copy over the example .env file as …
  source/elegant/.env.starter
  source/init.js
Labels: type: enhancement, version: 2.2, status: waiting on public comment

#46 Feature/upgrade guide
  source/elegant/package-lock.json
  source/elegant/src/navs/documentation.ts
  source/elegant/src/pages/docs/upgrade.mdx
Labels: type: enhancement, type: friction, status: in progress, version: 2.2, status: ready to merge

#44 Legal Namespace and Trademark Page
  .gitignore
  source/elegant/.env.example
  source/elegant/next.config.js
  source/elegant/src/pages/legal/trademark-policy.mdx
  source/elegant/src/utils/appInfo.js
Labels: type: enhancement, status: in progress, version: 2.2, status: in discussion
