Repository elegantframework/elegant-cli, pull requests merged in 2023-07, with the labels that each got.

#106 Created the development tools doc
  source/elegant/public/images/screenshot-2023-06-29-072644-Q2MT.png
  source/elegant/public/images/screenshot-2023-06-29-073136-g0Mz.png
  source/elegant/public/images/screenshot-2023-06-29-073410-U5OT.png
  source/elegant/src/pages/docs/development-tools.mdx
  source/elegant/src/pages/docs/release-notes.mdx
Labels: type: enhancement, version: 2.3, status: ready to merge

#105 Docs/brand page
  source/elegant/public/images/elegant-full-svg-c5Nj.svg
  source/elegant/src/pages/docs/release-notes.mdx
  source/elegant/src/pages/legal/brand.mdx
Labels: status: ready to merge

#110 Feature/add arrow icon to external links
  source/elegant/package-lock.json
  source/elegant/src/components/home/Footer.js
  source/elegant/src/config/authors.ts
  source/elegant/src/config/navigation.ts
  source/elegant/src/layouts/DocumentationLayout.js
  source/elegant/src/pages/docs/release-notes.mdx
Labels: type: enhancement, version: 2.3, status: ready to merge

#113 Feature/upgrade mdx loader to v2
  package-lock.json
  package.json
  source/elegant/next.config.mjs
  source/elegant/package-lock.json
  source/elegant/package.json
  source/elegant/rehype/withLinkRoles.mjs
  source/elegant/remark/utils.mjs
  source/elegant/remark/withExamples.mjs
  source/elegant/remark/withNextLinks.js
  source/elegant/remark/withSyntaxHighlighting.js
  source/elegant/remark/withSyntaxHighlighting.mjs
  source/elegant/remark/withTableOfContents.js
  source/elegant/remark/withTableOfContents.mjs
  source/elegant/src/components/CodeWindow.js
  source/elegant/src/components/ColorPaletteReference.js
  source/elegant/src/components/Editor.js
  source/elegant/src/components/Example.js
  source/elegant/src/components/Guides/TabBar.jsx
  source/elegant/src/components/Heading.js
  source/elegant/src/components/SnippetGroup.js
  source/elegant/src/components/Steps.js
  source/elegant/src/components/TabBar.js
  source/elegant/src/components/ThemeToggle.js
  source/elegant/src/css/docsearch.css
  source/elegant/src/hooks/useTop.js
  source/elegant/src/layouts/ContentsLayout.js
  source/elegant/src/layouts/DocumentationLayout.js
  source/elegant/src/layouts/SidebarLayout.js
  source/elegant/src/pages/_app.js
  source/elegant/src/pages/blog/2023-03-01-announcing-elegant-framework/index.mdx
  source/elegant/src/pages/blog/2023-04-05-elegant-framework-v2-0-alpha/index.mdx
  source/elegant/src/pages/blog/2023-04-20-the-future-is-markdown/index.mdx
  source/elegant/src/pages/blog/index.js
  source/elegant/src/pages/docs/contribution-guide.mdx
  source/elegant/src/pages/docs/release-notes.mdx
  source/elegant/src/pages/docs/theme.mdx
  source/elegant/src/scripts/build-rss.js
  source/elegant/src/utils/getAllPosts.js
  source/elegant/src/utils/mdxComponents.js
  source/elegant/src/utils/themeToggle.js
  source/elegant/tailwind.config.js
Labels: type: enhancement, type: friction, version: 2.3, status: waiting review, status: ready to merge

#107 the navigation and authors config to be under the '/config' namespace
  package-lock.json
  package.json
  source/elegant/package-lock.json
  source/elegant/src/config/Authors.ts
  source/elegant/src/config/Navigation.ts
  source/elegant/src/config/__tests__/Authors.test.ts
  source/elegant/src/config/authors.ts
  source/elegant/src/layouts/DocumentationLayout.js
  source/elegant/src/pages/blog/2023-03-01-announcing-elegant-framework/index.mdx
  source/elegant/src/pages/blog/2023-04-05-elegant-framework-v2-0-alpha/index.mdx
  source/elegant/src/pages/blog/2023-04-20-the-future-is-markdown/index.mdx
  source/elegant/src/pages/docs/release-notes.mdx
Labels: type: enhancement, version: 2.3, status: ready to merge

#116 Bugfix/video layout
  source/elegant/src/components/core/Videos/VideoPlayer.tsx
  source/elegant/src/components/core/Videos/__snapshots__/VideoPlayer.test.tsx.snap
Labels: type: bug, type: friction, version: 2.3, status: ready to merge

#122 Refactor/remove deprecated header
  source/elegant/src/components/Header.js
  source/elegant/src/components/ThemeToggle.js
  source/elegant/src/components/core/Navigation/NavPopover/NavPopover.tsx
  source/elegant/src/pages/index.js
Labels: version: 2.3, status: ready to merge
